// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<Record<string, any>>;

export function BrowseFolder():Promise<string>;

export function GetDrives():Promise<Array<main.DriveInfo>>;

export function GetLastReport():Promise<main.ScanReportDTO>;

export function ListQuarantine():Promise<Array<main.QuarantineItem>>;

export function MoveToQuarantine(arg1:Array<string>):Promise<main.MoveOutcome>;

export function Purge(arg1:boolean):Promise<main.MoveOutcome>;

export function PurgeSelected(arg1:Array<string>):Promise<main.MoveOutcome>;

export function PurgeSingle(arg1:string):Promise<main.MoveOutcome>;

export function Restore(arg1:Array<string>):Promise<main.MoveOutcome>;

export function RestoreSingle(arg1:string):Promise<main.MoveOutcome>;

export function Scan(arg1:string,arg2:string):Promise<main.ScanResult>;

export function Stats():Promise<Record<string, any>>;
