// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function BrowseFolder() {
  return window['go']['main']['App']['BrowseFolder']();
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetLastReport() {
  return window['go']['main']['App']['GetLastReport']();
}

export function ListQuarantine() {
  return window['go']['main']['App']['ListQuarantine']();
}

export function MoveToQuarantine(arg1) {
  return window['go']['main']['App']['MoveToQuarantine'](arg1);
}

export function Purge(arg1) {
  return window['go']['main']['App']['Purge'](arg1);
}

export function PurgeSelected(arg1) {
  return window['go']['main']['App']['PurgeSelected'](arg1);
}

export function PurgeSingle(arg1) {
  return window['go']['main']['App']['PurgeSingle'](arg1);
}

export function Restore(arg1) {
  return window['go']['main']['App']['Restore'](arg1);
}

export function RestoreSingle(arg1) {
  return window['go']['main']['App']['RestoreSingle'](arg1);
}

export function Scan(arg1, arg2) {
  return window['go']['main']['App']['Scan'](arg1, arg2);
}

export function Stats() {
  return window['go']['main']['App']['Stats']();
}
